GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphYmFsaXBlbHVkb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExMjg4NjksImV4cCI6MTY4MTEyODg5OX0.HdzuTLn-3KHnUTAuKVMv1Ag41a0v7h1nF7E0uYkdaRA

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmllbG11bm96Z2lsQGdtYWlsLmNvbSIsImlhdCI6MTY4MTEyODk1N30.ysYHHiAAWXvrf3C3VmdOkvXb4aPvWp1yizlCEUN1RIw"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImRhbmllbG11bm96Z2lsQGdtYWlsLmNvbSIsImlhdCI6MTY4MTEyODk1N30.ysYHHiAAWXvrf3C3VmdOkvXb4aPvWp1yizlCEUN1RIw"
}

###

#POST http://localhost:3000/login
#Content-Type: application/json

#{
#    "username": "Jim" 
#}