GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphYmFsaXBlbHVkb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExNTAwMjQsImV4cCI6MTY4MTE1MDA1NH0.K47BMR8pQNWKrEwL9s4frG9eP5gmZzlQh_GoH2iTUG4

###

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphYmFsaXBlbHVkb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExNDk5ODV9.rDB0oYIviErZWRJfW-PUu8BeM3T02qlZdGzZ-w60g-o"
}

###

POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphYmFsaXBlbHVkb0BnbWFpbC5jb20iLCJpYXQiOjE2ODExNDk5ODV9.rDB0oYIviErZWRJfW-PUu8BeM3T02qlZdGzZ-w60g-o"
}

###

#POST http://localhost:3000/login
#Content-Type: application/json

#{
#    "username": "Jim" 
#}
